[package]
name = "monkey_lib"
version = "0.1.0"
authors = ["jonnywalker"]

[dependencies]
  "maplit" = "*"
  "seahash" = "*"
  float-cmp = "0.2.3"
  readline = "*"
  libc = "*"

# [lib]
  # crate-type= ["staticlib", "rlib"]
